apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  labels:
    app: {{ .Release.Name }}
data:
  .env: |
    # SCRIPT ENV VARIABLES
    export DAPP_INSTANCES={{ .Values.erc20config.scriptEnv.dappInstances | default 1 }}
    export SHARE_CONTRACT={{ .Values.erc20config.scriptEnv.shareContract | default "false" }}
    export EXPOSE_UI_PORT_EXTERNALLY={{ .Values.erc20config.scriptEnv.exportUiPortExternally | default "false" }}
    export MAX_SLEEP_TIME={{ .Values.erc20config.scriptEnv.maxSleepTime | default 1 }}

    # ETH ENDPOINT
    export WEB3J_ETHCLIENT_PROTOCOL=http
    export WEB3J_ETHCLIENT_HOST={{ .Values.erc20config.ethEndpoint.host}}
    export WEB3J_ETHCLIENT_PORT=8545
    export WEB3J_ETHCLIENT_CORRELATE={{ .Values.erc20config.ethEndpoint.correlate | default "true" }}

    # WORKLOAD
    export WORKLOAD_TRANSACTIONS={{ .Values.erc20config.workload.transactions | default 100 }}
    export WORKLOAD_MODEL={{ .Values.erc20config.workload.model | default "CLOSED" }}
    export WORKLOAD_LOAD_FACTOR={{ .Values.erc20config.workload.loadFactor | default 1 }}
    export WORKLOAD_BATCH_SIZE={{ .Values.erc20config.workload.batchSize | default 10 }}

    # RECEIPT
    export WEB3J_RECEIPT_ATTEMPTS={{ .Values.erc20config.receipt.attempts | default 1 }}
    export WEB3J_RECEIPT_INTERVAL={{ .Values.erc20config.receipt.interval | default 1000 }}
    export WEB3J_RECEIPT_DEFER={{ .Values.erc20config.receipt.defer | default "false" }}
    export WEB3J_RECEIPT_CHECK_WRITE_TX_FAILED={{ .Values.erc20config.receipt.checkWriteTxFailed | default "true" }}
    export WEB3J_RECEIPT_RETRY_WRITE_TX_SLEEP={{ .Values.erc20config.receipt.retryWriteTxSleep | default 5 }}
    export WEB3J_RECEIPT_NO_WRITE_TX_RETRY={{ .Values.erc20config.receipt.noWriteTxRetry | default 5 }}

    # MISC
    export WEB3J_LOG_LEVEL={{ .Values.erc20config.misc.logLevel | default "DEBUG" }}
    export WEB3J_OKHTTP_READ_TIMEOUT={{ .Values.erc20config.misc.okhttpReadTimeout | default 20 }}

    # WAVEFRONT
    export MANAGEMENT_METRICS_EXPORT_WAVEFRONT_ENABLED={{ .Values.erc20config.wavefront.metricsExportWavefrontEnabled | default "false" }}
    export WAVEFRONT_TOKEN={{ .Values.erc20config.wavefront.token | default "4fd8bd2c-7a05-4177-a095-ef6d8100a779" }}
